var moment, sameDayOrNight, sameMonth;

moment = require('moment-timezone');

sameMonth = function(start, end) {
  return end.month() === start.month();
};

sameDayOrNight = function(start, end) {
  return end.day() === start.day() || ((end.diff(start, 'hours') < 24) && end.hours() < 8);
};

module.exports = function(_arg) {
  var end, endDate, start, startDate, timeFormat, timeZone;
  endDate = _arg.endDate, startDate = _arg.startDate, timeZone = _arg.timeZone, timeFormat = _arg.timeFormat;
  if (!timeZone) {
    timeZone = 'Europe/Stockholm';
  }
  if (!timeFormat) {
    timeFormat = '24';
  }
  start = moment(startDate).tz(timeZone);
  if (endDate) {
    end = moment(endDate).tz(timeZone);
    if (sameMonth(start, end)) {
      if (sameDayOrNight(start, end)) {
        if (timeFormat && timeFormat === '12') {
          return start.format('D MMM hh:mm A') + ' - ' + end.format('hh:mm A');
        } else {
          return start.format('D MMM HH:mm') + ' - ' + end.format('HH:mm');
        }
      } else {
        return start.format('D') + ' - ' + end.format('D MMM');
      }
    } else {
      return start.format('D MMM') + ' - ' + end.format('D MMM');
    }
  } else {
    if (timeFormat && timeFormat === '12') {
      return start.format('D MMM hh:mm A');
    } else {
      return start.format('D MMM HH:mm');
    }
  }
};

// ---
// generated by coffee-script 1.9.0
